name: Deployment

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy PhilNITS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload file to SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          source: "*"
          exclude: "./node_modules, ./.git, ./.github, /etc, /lib"
          target: "~/philnits.dcism.org/"
          overwrite: true

      - name: Build
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ~/philnits.dcism.org
            npm install
            npm run build
            npx pm2 delete philnits || true
            npx pm2 start npm --name 'philnits' -- start 
